version: '2'
networks:
  default:
    external:
      name: ggggg
services:
  php:
    build: .
    container_name: demotester_php
    image: demoteer:70
    privileged: false
    restart: unless-stopped
    tty: true
    volumes: 
      - .:/var/www/html